name: Node.js CI Demo

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '22'  # Match your local Node.js version

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Run your Express server (test only)
      - run: node index.js &
      
      # Step 5: Print confirmation
      - run: echo "Server should be running on port 30005"
